# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-16 00:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='date_joined',
            field=models.DateField(auto_now=True),
        ),
    ]
